### PR TITLE
fix: use GitHub isBinary field for binary detection

### LINKED ISSUE #203: Files mis-identified as binary artifacts
Via LFX Insights, this plugin causes the binary artifacts (OSPS-QA-05.01) check for [guacsec/guac](https://insights.linuxfoundation.org/project/guac/repository/guacsec-guac/security) to fail with:

> Suspected binaries found in the repository: excluded_from_copyright, TECHNICAL_ADVISORY_MEMBERS, Tiltfile, dockerignore

However!

* `excluded_from_copyright` does not exist in the repo (and apparently never has)
* `TECHNICAL_ADVISORY_MEMBERS` is a [plain text file](https://github.com/guacsec/guac/blob/main/TECHNICAL_ADVISORY_MEMBERS) (arguably CSV-shaped)
* `Tiltfile` is a [plain text configuration file](https://github.com/guacsec/guac/blob/main/Tiltfile) used by Tilt
* `dockerignore` is a [plain text configuration file](https://github.com/guacsec/guac/blob/main/dockerignore) used by Docker

### PR DESCRIPTION
**Pull request by pfeifferj**
Replace extension-based binary detection with GitHub's GraphQL isBinary field. The previous implementation flagged extensionless files as binary because the binaryExtensions map included an empty string entry. This caused false positives for common text files like OWNERS, Tiltfile, dockerignore, and TECHNICAL_ADVISORY_MEMBERS.

Fixes #203

### CODE REVIEW

**Comment by pfeifferj** [comment]
hi @eddie-knight sorry I only just saw your reply! 

I tested against `gradle/gradle`, and it correctly detected `gradle-wrapper.jar` as binary. 

thank you for sharing your test repo. I took a look at the behaviour: the first difference I noticed was the file sizes which led me down a bit of a rabbit hole, and while I couldn't find an official source on this, I observed that when `isTruncated: true`, the gh graphql api doesn't analyze content and returns `isBinary: null` instead of `true|false`. more digging seems to indicate that blobs are truncated if they exceed 512KB. again, no official docs on this, just trial and error + this old discussion thread [1] seems to vaguely corroborate this.

[1] https://github.com/orgs/community/discussions/23920

File: data/graphql-binary-check.go [hunk 1]
```diff
@@ -112,19 +61,95 @@ type GraphqlRepoTree struct {
...
+}
+
+func (bc *binaryChecker) isBinary(isBinaryPtr *bool, isTruncated bool, path string) bool {
+	if isBinaryPtr != nil {
+		return *isBinaryPtr
+	}
+	if isTruncated {
+		binary, err := bc.checkViaPartialFetch(path)
+		if err != nil {
+			bc.logger.Trace(fmt.Sprintf("failed to check binary status via partial fetch for %s: %s", path, err.Error()))
```
Comment (eddie-knight) [inline data/graphql-binary-check.go]: This makes sense to me.

But it seems like we have three states now: Pass / Fail / Unknown

Gemara assessment steps support returning an unknown state, which becomes a warning with a message instead of a false positive / false negative.

@pfeifferj do you want me to push to your branch to refactor the logic around this to support the three possibilities?

Comment (pfeifferj) [reply data/graphql-binary-check.go]: sure, that's fine for me :)

File: data/graphql-binary-check.go [hunk 2]
```diff
@@ -112,19 +61,95 @@ type GraphqlRepoTree struct {
...
+	if resp.StatusCode != http.StatusPartialContent && resp.StatusCode != http.StatusOK {
+		return false, fmt.Errorf("unexpected status: %d", resp.StatusCode)
+	}
+
+	content, err := io.ReadAll(resp.Body)
+	if err != nil {
+		return false, err
+	}
+
+	return hasNullBytes(content), nil
```
Comment (evankanderson) [inline data/graphql-binary-check.go]: You might want to look at MIME types as one way to separate e.g. `image/png` from `application/*`: https://pkg.go.dev/net/http#DetectContentType

**Review by eddie-knight — APPROVED** [review]
